### ISSUE TITLE
ZLauncher, PatchBuilder, ZLauncherUpdater

### ISSUE THREAD

**Issue by massdivide** [ZER0NIS/Gunz-Base#1]
I noticed you didn't include these into your repo, were you unable to convert them to 2019?

**Comment by b12f** [comment]
Bumping this

**Comment by PabloMonfort** [comment]
if you guys dont know how to script a launcher and a patcher then prolly should not be looking around this source codes...

**Comment by massdivide** [comment]
@PabloMonfort, You are like 3 years out of date friend, also, nobody is "searching" I was offering to supply the MAIET converted source code for VS2019.
