### ISSUE TITLE
Widescreen support

### ISSUE THREAD

**Issue by dansheen21** [ZER0NIS/Gunz-Base#2]
Hi,

I hope you are still supporting this source. I tried to apply widescreen support, as in the resolution list you don't even have 1920x1080 (which is a widely used resolution). The guide I tried to use was this: https://forum.ragezone.com/f497/enable-widescreen-support-972230/

But the source just seems to ignore it lol, If you could add widescreen support that would be amazing :-).

**Comment by ZER0NIS** [comment]
ZERONIS#9999

**Comment by ZER0NIS** [comment]
Done
